### ISSUE TITLE
invalid new-expression of abstract class  type

### ISSUE THREAD

**Issue by wangzheqie** [stevenlovegrove/Pangolin#252] opened 2017-06-11 13:20 UTC
There are always have a problem that list as follows : 

----------------------------------------------separating  line --------------------------------------------------------------
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp: In member function ‘virtual std::unique_ptr<pangolin::VideoInterface> pangolin::RegisterOpenNi2VideoFactory()::OpenNI2VideoFactory::Open(const pangolin::Uri&)’:
/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:656:71: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                 nivid = new OpenNi2Video(pangolin::PathExpand(uri.url));

/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:658:54: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                 nivid = new OpenNi2Video(stream_modes);
                                                      ^

/home/qie/softs/ros_slam/Pangolin/src/video/drivers/openni2.cpp:660:79: error: invalid new-expression of abstract class type ‘pangolin::OpenNi2Video’
                nivid = new OpenNi2Video(default_dim, default_roi, default_fps);
                                                                              ^

**Comment by stevenlovegrove** [comment] 2017-06-14 04:35
This is a duplicate of https://github.com/stevenlovegrove/Pangolin/issues/251 which I have just pushed a fix for. Thanks for reporting.

**Closed by stevenlovegrove** 2017-06-14 04:35 UTC
