### ISSUE TITLE
Can not find "unistd.h"

### ISSUE THREAD

**Issue by PlayerUsr** [stevenlovegrove/Pangolin#205] opened 2017-02-12 21:17 UTC
Please solution ?

**Comment by stevenlovegrove** [comment] 2017-02-13 17:30
Master is broken on windows right now. I'd recommend checking out a slightly older version:
https://github.com/stevenlovegrove/Pangolin/commit/8b8b7b96adcf58ac2755dedd3f681fc512385af0

**Comment by stevenlovegrove** [comment] 2017-02-13 17:31
Duplicate of #204

**Closed by stevenlovegrove** 2017-02-13 17:31 UTC

**Comment by PlayerUsr** [comment] 2017-02-20 19:42
it's not work :(
