### ISSUE TITLE
Blank screen in Windows. Works fine on Linux and OSX.

### ISSUE THREAD

**Issue by Aashikr** [stevenlovegrove/Pangolin#381] opened 2018-06-29 20:55 UTC
All the examples show a blank screen. When I did bisect it looks like the issue is caused after the patch **Introduce Window Factory**(2cbc1b4da0332c7233438895b9a60833e0b57606) was merged. Screenshot of HelloPangolin is attached.

<img width="1902" alt="pangolinhellopangolin" src="https://user-images.githubusercontent.com/5509726/42114455-f9883e90-7ba3-11e8-973c-5c1c8678b796.PNG">

**Comment by stevenlovegrove** [comment] 2018-06-30 21:18
Could this issue be a duplicate of https://github.com/stevenlovegrove/Pangolin/issues/367 ?

i.e. if you resize the window, do you get something?

**Closed** 2021-09-03 04:45 UTC
