### ISSUE TITLE
openGL error

### ISSUE THREAD

**Issue by huangju91** [stevenlovegrove/Pangolin#149] opened 2016-09-21 06:30 UTC
Hello@stevenlovegrove , I  cmaked pangolin to vs2013 and all built it successfully，but when I use it in orb-slam2 ，the following error turns out
“ OpenGL Error： XX （1280）
In：D：\orb2Depen\Pangolin\include\pangolin/gl/gl.hpp, line 189”
Though this error did not stop my running program, I still wonder why.

**Comment by stevenlovegrove** [comment] 2016-09-30 19:54
It's possible this has been fixed in 49aa3668da58a793e434807b8e2d167824661225. Otherwise, this is likely to be a warning generated from a previous OpenGL error unrelated to Pangolin.

**Comment by fsrajer** [comment] 2016-10-05 13:23
Hi @huangju91, I seem to be getting the same error. Did the mentioned commit fix your problem. It did not for me. 
Hi @stevenlovegrove, I am using Pangolin via ElasticFusion. The error seems to be generated by this line:
[https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/gl.hpp#L176](url)
Any ideas what could be causing this? It does not directly cause a crash but a different call to opengl later on crashes so I assume that there will be some connection.

**Comment by fsrajer** [comment] 2016-10-05 14:03
OK, I have fixed both, the crash and the opengl error message. My laptop was for some reason choosing integrated Intel graphics instead of NVIDIA and the code was using some functions which were not supported by the Intel graphics. So I simply opened NVIDIA control panel and set NVIDIA graphics card to be used at all times.

**Comment by stevenlovegrove** [comment] 2016-10-06 05:01
Thanks for the update. I'll close this issue.

**Closed by stevenlovegrove** 2016-10-06 05:01 UTC

**Comment by M1234Thomas** [comment] 2016-11-04 13:37
Hello,

I am getting an error as follows.

OpenGL Error: XX (1282)
In: \ElasticFusion\Pangolin-master\include\pangolin/gl/gl.hpp, line 562

I have checked the graphics card and is set to use NVIDIA to use all the times. 
I can not figure out what the issue is.

**Comment by anatoly-spb** [comment] 2017-03-02 08:08
When I run ElasticFusion build with Visual Studio 2013 on Windows 7 64bit I have problem with the draw_global_surface.vert shader:

```
Creating live capture... failed!
DeviceOpen using default: no devices found
GLSL Shader compilation failed: H:/tmp/ef/src/ElasticFusion/Core/src/Shaders/dra
w_global_surface.vert:
ERROR: 0:21: 'location' : syntax error parse error


GLSL Program link failed: Geometry shader object: no attached vertex shader obje
ct.

OpenGL Error: XX (1280)
In: H:\tmp\ef\src\Pangolin\include\pangolin/gl/gl.hpp, line 192
```
What is wrong?

**Comment by Buzzroid** [comment] 2017-07-08 01:53
@fsrajer Thanks for the solution. You're the guru.

**Comment by szuer2017** [comment] 2019-06-11 03:55
> Hello,
> 
>ElasticFusion could be compiled sucessfully  on my Nvidia TX2  ,  but  I am getting an error as follows:
> 
> OpenGL Error: XX (500)
> In:/ElasticFusion/deps/Pangolin/include/pangolin/gl/gl.hpp, line 212
> 

> I can not figure out what the issue is.

**Comment by shoujieqiu** [comment] 2019-11-01 13:07
Actually,I always have this error,and I can't fix it.I wonder if anybody could help to solve it?

`Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.GLSL Shader compilation failed: <string>:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

OpenGL Error 500: GL_INVALID_ENUM: An unacceptable value is specified for an enumerated argument.
In: /usr/local/include/pangolin/gl/gl.hpp, line 205`

**Comment by shoujieqiu** [comment] 2019-11-01 13:09
And my computer is "RTX 2070,ubuntu 16.04,glfw 3.3"

**Comment by BruceWANGDi** [comment] 2020-10-28 12:25
@shoujieqiu Try to use this command 'MESA_GL_VERSION_OVERRIDE=3.3 ./ElasticFusion'. It may work.
I have met this issue for so long. Some said Nvidia-driver causes this issue, which the .run profile downloaded on the official website can't work. Using the command on the system terminal may be helpful.
