### ISSUE TITLE
Pangolin make error！

### ISSUE THREAD

**Issue by sylin211** [stevenlovegrove/Pangolin#372] opened 2018-06-20 10:55 UTC
Some errors occur when I make pangolin which I can't handle：

slam1@slam1-desktop:~/3rdParty/Pangolin-master/build$ make -j4
Scanning dependencies of target pangolin
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/video/drivers/pango_video_output.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/display/display.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/video/video.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/tools/video_viewer.cpp.o
[  4%] Building CXX object src/CMakeFiles/pangolin.dir/display/device/display_x11.cpp.o
In file included from /usr/include/c++/4.8/memory:64:0,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/factory/factory_registry.h:30,
                 from /home/slam1/3rdParty/Pangolin-master/src/video/drivers/pango_video_output.cpp:28:
/usr/include/c++/4.8/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = pangolin::memstreambuf; _Args = {pangolin::memstreambuf}]’:
/usr/include/c++/4.8/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<pangolin::memstreambuf*>; _ForwardIterator = pangolin::memstreambuf*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.8/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<pangolin::memstreambuf*>; _ForwardIterator = pangolin::memstreambuf*]’
/usr/include/c++/4.8/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<pangolin::memstreambuf*>; _ForwardIterator = pangolin::memstreambuf*; _Tp = pangolin::memstreambuf]’
/usr/include/c++/4.8/bits/stl_uninitialized.h:281:69:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = pangolin::memstreambuf*; _ForwardIterator = pangolin::memstreambuf*; _Allocator = std::allocator<pangolin::memstreambuf>]’
/usr/include/c++/4.8/bits/vector.tcc:415:43:   required from ‘void std::vector<_Tp, _Alloc>::_M_emplace_back_aux(_Args&& ...) [with _Args = {long unsigned int&}; _Tp = pangolin::memstreambuf; _Alloc = std::allocator<pangolin::memstreambuf>]’
/usr/include/c++/4.8/bits/vector.tcc:101:54:   required from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {long unsigned int&}; _Tp = pangolin::memstreambuf; _Alloc = std::allocator<pangolin::memstreambuf>]’
/home/slam1/3rdParty/Pangolin-master/src/video/drivers/pango_video_output.cpp:210:58:   required from here
/usr/include/c++/4.8/bits/stl_construct.h:75:7: error: use of deleted function ‘pangolin::memstreambuf::memstreambuf(pangolin::memstreambuf&&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from /home/slam1/3rdParty/Pangolin-master/src/video/drivers/pango_video_output.cpp:30:0:
/home/slam1/3rdParty/Pangolin-master/include/pangolin/utils/memstreambuf.h:9:8: note: ‘pangolin::memstreambuf::memstreambuf(pangolin::memstreambuf&&)’ is implicitly deleted because the default definition would be ill-formed:
 struct memstreambuf : public std::streambuf
        ^
In file included from /usr/include/c++/4.8/ios:43:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/utils/format_string.h:30,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/utils/assert.h:31,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/platform.h:80,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/utils/uri.h:30,
                 from /home/slam1/3rdParty/Pangolin-master/include/pangolin/factory/factory_registry.h:34,
                 from /home/slam1/3rdParty/Pangolin-master/src/video/drivers/pango_video_output.cpp:28:
/usr/include/c++/4.8/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /home/slam1/3rdParty/Pangolin-master/src/video/drivers/pango_video_output.cpp:30:0:
/home/slam1/3rdParty/Pangolin-master/include/pangolin/utils/memstreambuf.h:9:8: error: within this context
 struct memstreambuf : public std::streambuf
        ^
make[2]: *** [src/CMakeFiles/pangolin.dir/video/drivers/pango_video_output.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

**Comment by NikolausDemmel** [comment] 2018-06-20 11:08
Duplicate of #371?

**Comment by sylin211** [comment] 2018-06-20 11:35
Thank you very much! I copy an old version of Pangolin from another PC and it builds successfully.

**Closed** 2018-06-20 11:36 UTC

**Comment by stevenlovegrove** [comment] 2018-06-21 05:56
Should be fixed in https://github.com/stevenlovegrove/Pangolin/commit/cdeb97c03824cdefeaa617800c033c0c03ee5902
