### ISSUE TITLE
Plotting X versus Y

### ISSUE THREAD

**Issue by MichaelBrazeau** [stevenlovegrove/Pangolin#463] opened 2019-01-02 02:07 UTC
There seems to be no way to set up Pangolin to plot an given Y, based on the given x

**Comment by stevenlovegrove** [comment] 2019-01-15 04:51
It is possible. You must call Plotter::AddSeries() and give the x_expr and y_expr explicitly. Check the documentation for that method.

**Comment by stevenlovegrove** [comment] 2021-09-03 20:40
Closing as duplicate of #456

**Closed by stevenlovegrove** 2021-09-03 20:40 UTC
