### ISSUE TITLE
Pangolin framebuffer error

### ISSUE THREAD

**Issue by jerrywiston** [stevenlovegrove/Pangolin#239] opened 2017-05-03 05:32 UTC
Hello,

when I run ORB_SLAM2(https://github.com/raulmur/ORB_SLAM2), I get following error 

terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options

#74 says we have to comment this two lines
//GLX_SAMPLE_BUFFERS  , 1,
//GLX_SAMPLES         , 4, 
 but I can't find this two lines in Pangolin
Why I still got this error?

**Comment by stevenlovegrove** [comment] 2017-05-22 20:24
I don't know, sorry. This error seems to mostly occur on unusual system configurations (such as odd X-servers, VM's, etc). You may have to debug the code yourself (display_x11.cpp, line 116)

**Comment by Gyiming** [comment] 2017-08-03 17:00
Hi, Have you solved this problem? I met the same problem on ubuntu14.04. It works fine on 16.04 for me.

**Comment by holovincent** [comment] 2017-11-01 03:26
I got the same error. Do you have progress on this? Thanks.

**Comment by stevenlovegrove** [comment] 2018-05-17 06:07
This is a duplicate of #260 - closing.

**Closed by stevenlovegrove** 2018-05-17 06:07 UTC
