### ISSUE TITLE
AttributeError: module 'Pangolin' has no attribute 'CreateWindowAndBind'

### ISSUE THREAD

**Issue by venkateshtata** [stevenlovegrove/Pangolin#557] opened 2019-10-07 10:43 UTC
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/venkatesh/slam/display.py", line 39, in viewer_thread
    self.viewer_init(1024, 768)
  File "/home/****/slam/display.py", line 44, in viewer_init
    pangolin.CreateWindowAndBind('Map Viewer', w, h)
AttributeError: module 'Pangolin' has no attribute 'CreateWindowAndBind'

**Comment by christian-rauch** [comment] 2019-10-30 14:34
Does this only happen with the python bindings or do you also get compilation errors with the C++ example programs?

**Comment by ngthanhtin** [comment] 2019-11-28 09:20
I encountered the same problem, did you fix it ?
@christian-rauch I built (cmake --build .) successfully but when I use a function such as "pangolin.CreateWindowAndBind", it leads to failure. Do you have any advice ?

**Comment by ngthanhtin** [comment] 2019-11-29 03:44
@venkateshtata have you found any solution ?

**Comment by christian-rauch** [comment] 2019-11-29 11:38
I cannot reproduce this. The scripts in `pyexamples` work. E.g. `python3 SimpleDisplay.py` spawns a window and shows an interactive cube.
@ngthanhtin Do the C++ and python example program run on your setup?

**Comment by ngthanhtin** [comment] 2019-11-29 15:24
@christian-rauch I built successfully with C++ (I set PANGOLIN_WITH_PYTHON=False), but when I set this to True I came across bugs. Anyway, I have switch to https://github.com/uoip/pangolin repo and built successfully with it. Thank you for your support :D

**Comment by lloydrayner** [comment] 2019-12-01 12:05
+1 also getting this error :(

**Comment by mar836924042** [comment] 2020-05-10 10:31
Has anyone solved the problem?  I get the same issue when I run pyexamples/SimpleDisplay.
AttributeError: module 'pypangolin' has no attribute 'CreateWindowAndBind'

**Comment by blarkj** [comment] 2020-07-21 22:01
Even I am getting the same error.

**Comment by ekmungi** [comment] 2020-11-11 16:58
I am getting the same error when I installed pangolin using anaconda.

`conda install -c bioconda pangolin`

I cannot run the SimpleDisplay example. Any help would be appreciated!

**Comment by ekgus0909** [comment] 2021-03-15 01:59
I solved this problem
you are install conda -> conda uninstall pangolin
and you follow here ==> https://github.com/uoip/pangolin 
----------------------------------------------------------------------------
git clone https://github.com/uoip/pangolin.git
cd pangolin
mkdir build
cd build
cmake ..
make -j8
cd ..
python setup.py install

**Comment by shuangnan** [comment] 2021-08-13 08:28
> ## I solved this problem
> you are install conda -> conda uninstall pangolin
> and you follow here ==> https://github.com/uoip/pangolin
> git clone https://github.com/uoip/pangolin.git
> cd pangolin
> mkdir build
> cd build
> cmake ..
> make -j8
> cd ..
> python setup.py install

I just do this, but still can't import pangolin.
can you tell me how did you success? 
thanks!

**Comment by shuangnan** [comment] 2021-08-13 08:32
> Has anyone solved the problem? I get the same issue when I run pyexamples/SimpleDisplay.
> AttributeError: module 'pypangolin' has no attribute 'CreateWindowAndBind'

Hi,
did you solve this problem? i meet the same problem

**Comment by stevenlovegrove** [comment] 2021-09-07 21:02
I have done quite a bit of work in the last few commits to make python use much simpler (e.g. 1b372f672884287dd7313882bf674ce2020bf50a).

You can now build the pypangolin_pip_install target to install python and avoid the many versioning gotchas. It will also print very explicitly the version of python that it has been built and installed for and the README now describes how to change the version during the cmake step. Hopefully this all adds up to a better user experience. I'll close this now. Please reopen if you experience this again on the master branch.

**Closed** 2021-09-07 21:02 UTC
