### ISSUE TITLE
VS2022 Build issue

### ISSUE THREAD

**Issue by felpic** [stevenlovegrove/Pangolin#748] opened 2022-03-16 08:32 UTC
Platform: Windows 10
Compiler: MSVC

I have been trying for a while, but I haven't managed to build Pangolin. I get the following errors repeated many times for different packages: atomic, xmemory and xpolymorphic_allocator at least.

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(206,9): error C2039: '
_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(206,9): error C3861: '
_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(221,9): error C2039: '
_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(221,9): error C3861: '
_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(237,9): error C2039: '
_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\atomic(237,9): error C3861: '
_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
  gl.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(154,5): error C2039:
'_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(154,5): error C3861:
'_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(164,5): error C2039:
'_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(164,5): error C3861:
'_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(1203,9): error C2039:
 '_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xmemory(1203,1): error C3861:
 '_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xpolymorphic_allocator.h(146,
13): error C2039: '_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xpolymorphic_allocator.h(146,
1): error C3861: '_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xpolymorphic_allocator.h(152,
13): error C2039: '_invalid_parameter': is not a member of '`global namespace'' [C:\ORB-SLAM3\Pangolin\build\pypangolin
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\xpolymorphic_allocator.h(152,
1): error C3861: '_invalid_parameter': identifier not found [C:\ORB-SLAM3\Pangolin\build\pypangolin.vcxproj]
```

**Comment by felpic** [comment] 2022-03-16 08:58
Brief update. This seems to be a fairly common issue with VS2022, which could be somehow related to pybind11:
https://github.com/microsoft/onnxruntime/issues/9735
https://github.com/microsoft/STL/issues/2335
https://github.com/pybind/pybind11/issues/3459

I am new to this, so I don't really understand what is going on and if and how I can fix it. Any help would be greatly appreciated. Otherwise, I might just try to install an older version of Visual Studio

**Comment by Manuel-Meyer** [comment] 2022-08-16 10:18
Have you found a solution? I have the same problem with VS2019.

**Comment by christian-rauch** [comment] 2024-01-24 21:18
Windows + MSVC is now part of the CI pipeline again (https://github.com/stevenlovegrove/Pangolin/pull/899). This should make sure that this builds.

Apart from this, I cannot see how this is caused by Pangolin. `_invalid_parameter` is nothing that appears in the Pangolin code.

I am closing this now. But feel free to reopen and send a PR to the CI configuration to reproduce this.

**Closed by christian-rauch** 2024-01-24 21:18 UTC
