### ISSUE TITLE
Target "pango_display" links to target "Eigen3::Eigen" but the target was not found. 

### ISSUE THREAD

**Issue by YangZhouDL** [stevenlovegrove/Pangolin#720] opened 2021-12-17 11:00 UTC
Hello,guys!I am following the "Read.md" to install the Pangolin,when I try to "cmake .."under the directory "build",I meet an error as the picture show:
![image](https://user-images.githubusercontent.com/92163060/146533830-cc863f14-e64e-476b-a474-1189a1432d93.png)
I have searched some methods but all failed.
My eigen version is 3.2.92,as is shown below.
![image](https://user-images.githubusercontent.com/92163060/146534169-d85fc46e-6e94-4617-ba77-c57697171991.png)
I don't know if the version have effects.
What is more,I have update my cmake to the 3.22.1,as is shown below.
![image](https://user-images.githubusercontent.com/92163060/146534465-38e57c56-57e9-401d-a0cd-1d3e4bbc9122.png)
And my ros version is 16.04,I am running it in virtual box.
I am new to Ubuntu and ros,so it maybe hard for me to solve this promble,please help me!

**Comment by YangZhouDL** [comment] 2021-12-17 11:29
Alright,I have just solved this problem by updating my eigen version to 3.3.9,thank you,guys.

**Comment by juyebshin** [comment] 2021-12-28 08:38
I'm having same issue, but updating eigen version to 3.3.9 does not solve this issue. Any other solution?

**Comment by juyebshin** [comment] 2021-12-28 08:52
I think this issue is happening in version 0.6, using version 0.5 solved

**Comment by jfenton888** [comment] 2022-02-08 20:04
> 
@YangZhouDL
How did you update your version of Eigen to 3.3.9? I am trying the same thing now but can't seem to get any solutions I find to work.

**Comment by YangZhouDL** [comment] 2022-02-12 02:15
@jfenton888 
**-- Selected Python: '/usr/bin/python2.7'. cmake --build . -t pypangolin_pip_install to use pypangolin module.**
This sentence seems to recommand you to intall some dependency.
I follw this guidance to update my eigen:
https://blog.csdn.net/DeepOscar/article/details/105421701
This blog is written in Chinese,maybe you need to translate,hope it may help.

**Comment by minrui-hust** [comment] 2022-04-18 04:14
Eigen is a pure header lib, why pangolin need libeigen?what is libeigen?

**Comment by christian-rauch** [comment] 2022-04-19 15:21
Duplicate of https://github.com/stevenlovegrove/Pangolin/issues/711.

If you do not have `Eigen3Config.cmake` anywhere on your system, you probably have to install [`libeigen3-dev`](https://packages.ubuntu.com/focal/all/libeigen3-dev/filelist).

**Closed** 2022-04-20 10:05 UTC

**Comment by stevenlovegrove** [comment] 2022-04-26 00:09
This PR https://github.com/stevenlovegrove/Pangolin/pull/754 from @NikolausDemmel might explain and fix some of the Eigen finding issues some people experience for projects downstream of Pangolin.

**Comment by luckydipper** [comment] 2023-02-05 13:16
Compiling with cmake is ok.
But compiling with emscripten has same essue...
I've followed the readme file samely. Emscripten (Compile for web)
After I chat ```emcmake cmake ..``` in build-em.
```
configure: cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/qhrqufdlek/tools/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/qhrqufdlek/tools/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
CMake Error at components/pango_geometry/CMakeLists.txt:6 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:114 (include)


-- Configuring incomplete, errors occurred!
See also "/home/qhrqufdlek/Pangolin/build-em/CMakeFiles/CMakeOutput.log".
emcmake: error: 'cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/qhrqufdlek/tools/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/home/qhrqufdlek/tools/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads' failed (returned 1)
```

my environment
```
ubuntu 20.04

cat /usr/include/eigen3/Eigen/src/Core/util/Macros.h | grep VERSION
-> eigen 3.3.7 (use libeigen-dev) 
```
