### ISSUE TITLE
error while building Pangolin in ubuntu16.04

### ISSUE THREAD

**Issue by jeff210096** [stevenlovegrove/Pangolin#746] opened 2022-03-09 13:46 UTC
Hello guys, I got this error while the building the Pangolin. Can anyone help me?

[ 19%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
/home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp: In member function ‘virtual void pangolin::X11Window::ProcessEvents()’:
/home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:403:12: error: no matching function for call to ‘pangolin::MouseEvent::MouseEvent(<brace-enclosed initializer list>)’
            });
            ^
In file included from /home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: pangolin::MouseEvent::MouseEvent()
 struct PANGOLIN_EXPORT MouseEvent : public WindowInputEvent
                        ^
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 0 arguments, 5 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: constexpr pangolin::MouseEvent::MouseEvent(const pangolin::MouseEvent&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 1 argument, 5 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: constexpr pangolin::MouseEvent::MouseEvent(pangolin::MouseEvent&&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 1 argument, 5 provided
/home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:413:17: error: no matching function for call to ‘pangolin::MouseMotionEvent::MouseMotionEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: pangolin::MouseMotionEvent::MouseMotionEvent()
 struct PANGOLIN_EXPORT MouseMotionEvent : public WindowInputEvent
                        ^
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 0 arguments, 3 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(const pangolin::MouseMotionEvent&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(pangolin::MouseMotionEvent&&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:418:17: error: no matching function for call to ‘pangolin::MouseMotionEvent::MouseMotionEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: pangolin::MouseMotionEvent::MouseMotionEvent()
 struct PANGOLIN_EXPORT MouseMotionEvent : public WindowInputEvent
                        ^
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 0 arguments, 3 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(const pangolin::MouseMotionEvent&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(pangolin::MouseMotionEvent&&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:471:17: error: no matching function for call to ‘pangolin::KeyboardEvent::KeyboardEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/t1102/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: pangolin::KeyboardEvent::KeyboardEvent()
 struct PANGOLIN_EXPORT KeyboardEvent : public WindowInputEvent
                        ^
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 0 arguments, 5 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: constexpr pangolin::KeyboardEvent::KeyboardEvent(const pangolin::KeyboardEvent&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 1 argument, 5 provided
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: constexpr pangolin::KeyboardEvent::KeyboardEvent(pangolin::KeyboardEvent&&)
/home/t1102/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 1 argument, 5 provided
CMakeFiles/pango_windowing.dir/build.make:66: recipe for target 'CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o' failed
make[2]: *** [CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o] Error 1
CMakeFiles/Makefile2:624: recipe for target 'CMakeFiles/pango_windowing.dir/all' failed
make[1]: *** [CMakeFiles/pango_windowing.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by christian-rauch** [comment] 2022-04-12 10:44
Generally, Ubuntu 16.04 is not supported anymore. Try to follow the instructions on Ubuntu 20.04 and see if your problem still persists.

I don't see these compilation errors on my side and the CI also passes.

**Comment by X-NEARS** [comment] 2022-04-14 15:00
[jeff210096]You can refer to [jfenton888](https://github.com/jfenton888) commented [on 12 Feb](https://github.com/stevenlovegrove/Pangolin/pull/715#issuecomment-1036597183) answer.
I'm in Ubuntu 18.04 encountered the same error，I solved the problem according to this(https://github.com/stevenlovegrove/Pangolin/pull/715) suggestion.

git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
./scripts/install_prerequisites.sh recommended
git checkout v0.6

mkdir -p build && cd build
cmake .. -DEigen3_DIR=$HOME/eigen-3.3.9/build
cmake --build

**Comment by christian-rauch** [comment] 2022-04-14 15:07
I don't see how the (now solved) wayland compilation issues in #715 are related to this issue here.

Is the issue with Eigen3? You shouldn't need to install Eigen3 manually, the system version should work too.

**Comment by christian-rauch** [comment] 2022-04-19 15:23
This is a duplicate of https://github.com/stevenlovegrove/Pangolin/issues/676.

**Closed** 2024-01-24 21:13 UTC
