### ISSUE TITLE
undefined reference to '_glapi_tls_Current'

### ISSUE THREAD

**Issue by KivenLing** [stevenlovegrove/Pangolin#718] opened 2021-12-13 13:33 UTC
when I run 
cmake --build .

Linking CXX executable tutorial_5_gl_intro_view_transforms error.
/usr/lib/x86_64-linux-gnu/libOpenGL.so：undefined reference to '_glapi_tls_Current'

**Comment by thinhngo-x** [comment] 2021-12-16 14:49
Hi, have u fixed it ?

I have the same error running on a gcloud VM instance

**Comment by hbwanghang** [comment] 2022-02-27 06:22
Hi，have you fixed it?

**Comment by hbwanghang** [comment] 2022-02-27 06:33
> Hi, have u fixed it ?
> 
> I have the same error running on a gcloud VM instance

hi,have u fixed it?

**Comment by stevenlovegrove** [comment] 2022-03-01 19:54
Duplicate of #738

**Closed by stevenlovegrove** 2022-03-01 19:54 UTC

**Comment by AntonioMacaronio** [comment] 2024-01-26 23:19
this is not fixed, i am having the same issues on a google cloud VM when installing colmap, which relies on this package

**Comment by christian-rauch** [comment] 2024-01-27 00:02
> this is not fixed, i am having the same issues on a google cloud VM when installing colmap, which relies on this package

Nobody said it's fixed. Just follow up on the suggestions in the original issue and check if the symbol is defined in the linked libraries. The best would be to provide something reproducible, e.g. via a CI pipeline or a Dockerfile.

**Comment by AntonioMacaronio** [comment] 2024-01-27 01:21
If anyone is still running into this issue, there is a solution available [here](https://github.com/colmap/colmap/issues/1271)!

**Comment by christian-rauch** [comment] 2024-01-29 20:40
> If anyone is still running into this issue, there is a solution available [here](https://github.com/colmap/colmap/issues/1271)!

Thanks for following through with this. Which particular comment in the issue resolved your issue? Did reinstalling the Debian packages (https://github.com/colmap/colmap/issues/1271#issuecomment-926930890) help or did you have to compile and install [`libglvnd`](https://github.com/NVIDIA/libglvnd) from source (https://github.com/colmap/colmap/issues/1271#issuecomment-931900582)? I would like to add this workaround to the README.

In any case, can I assume that this is an issue with the Debian package in Ubuntu and not with Pangolin?
