### ISSUE TITLE
Building Tests requested, but Catch2 library not found.

### ISSUE THREAD

**Issue by Antony666** [stevenlovegrove/Pangolin#728] opened 2022-01-18 02:49 UTC
I am trying to build Pangolin on Ubuntu 16.04 LTS, but get an error when running cmake .. in the build folder

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
CMake Warning at CMakeLists.txt:75 (message):
  Building Tests requested, but Catch2 library not found.

CMake Error at components/pango_geometry/CMakeLists.txt:3 (find_package):
  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

@stevenlovegrove can you give me a advice??

**Comment by christian-rauch** [comment] 2022-02-14 11:56
`Catch2` is an optional dependency for tests. You can ignore this if you don't need tests. For Eigen follow the procedure in https://github.com/stevenlovegrove/Pangolin/pull/715#issuecomment-1036597183. Keep in mind that Ubuntu 16.04 is EOL and unsupported. You may need to install additional software to make the latest Pangolin run on 16.04.

**Comment by stevenlovegrove** [comment] 2022-02-18 04:40
I'll close this as a duplicate of #715 as @christian-rauch points out.

**Closed by stevenlovegrove** 2022-02-18 04:40 UTC
